[package]
name    = "schemahub-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "schemahub"
path = "src/main.rs"

[dependencies]
schemahub-api = { path = "../schemahub-api" }
tokio    = { workspace = true }
tonic    = { workspace = true }
prost    = { workspace = true }
clap     = { workspace = true }
anyhow   = { workspace = true }
serde    = { workspace = true }
toml     = { workspace = true }
bytes    = { workspace = true }
uuid     = { workspace = true }
