[package]
name    = "schemahub-core"
version = "0.1.0"
edition = "2021"

[dependencies]
schemahub-types   = { path = "../schemahub-types" }
schemahub-storage = { path = "../schemahub-storage" }
prost             = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
uuid              = { workspace = true }

[dev-dependencies]
schemahub-storage        = { path = "../schemahub-storage" }
schemahub-plugin-protobuf   = { path = "../schemahub-plugin-protobuf" }
schemahub-plugin-flatbuffers = { path = "../schemahub-plugin-flatbuffers" }
schemahub-plugin-openapi    = { path = "../schemahub-plugin-openapi" }
bytes                    = { workspace = true }
uuid                     = { workspace = true }
